import glob
import SCons.Defaults
import SCons
import os

baseDir = os.path.abspath( "." )

version = "1.0.0"

defines = ["VERSION=" + '"\\"' + version + '\\""']
compileFlags = ["-Wall", "-Wextra", "-std=c++17", "-O2", "-Wno-unused-parameter"]
includePaths = ["include", "/usr/include/libusb-1.0"]
libs = [
    "pixyusb",
    "boost_thread",
    "boost_chrono",
    "boost_system",
    "usb-1.0",
    "PocoNet",
    "PocoFoundation",
    "PocoUtil",
    "pthread"
]
sourceFiles = glob.glob( os.path.join( "src", "*.cpp" ) )

exe = os.path.join( baseDir, "bin", "pixy_cam" )
fakeExe = os.path.join( baseDir, "bin", "fake_pixy_cam" )

env = Environment(
    tools= ["default", "gcc", "g++"],
    CPPDEFINES=defines,
    CPPPATH = includePaths,
    CXXFLAGS = compileFlags,
    LIBS = libs,
    BINDIR = os.path.join( baseDir, "bin" )
)

realEnv = env.Clone(
    OBJPREFIX = os.path.join( baseDir, "obj", "real" ) + "/",
)

fakeEnv = env.Clone(
    OBJPREFIX = os.path.join( baseDir, "obj", "fake" ) + "/",
)
fakeEnv.Append( CPPDEFINES = ["FAKE_CAMERA"] )

exeTarget = realEnv.Program( target=exe, source=sourceFiles )
Clean( exeTarget, [os.path.join(realEnv['BINDIR']), os.path.join(realEnv['OBJPREFIX'])])

fakeTarget = fakeEnv.Program( target=fakeExe, source=sourceFiles )
Clean( fakeTarget, [os.path.join(fakeEnv['BINDIR']), os.path.join(fakeEnv['OBJPREFIX'])])

Alias( "build", exeTarget )
Alias( "build_fake", fakeTarget )
Default( "build" )
